CREATE DEFINER=`root`@`localhost` PROCEDURE `INS_GENERALES` (IN `PV_NOM_REPORTE` VARCHAR(255), IN `PI_NOM_USUARIO` VARCHAR(255), IN `PV_DES_REPORTE` VARCHAR(255), IN `PI_COD_FORMATO` BIGINT(20), IN `PV_FEC_DESDE` DATETIME, IN `PV_FEC_HASTA` DATETIME)  BEGIN
START TRANSACTION;
-- INSERTANDO EN LA TABLA AGENDA
INSERT INTO smartbanck.RP_GENERALES(
   NOM_REPORTE 
  ,NOM_USUARIO 
  ,DES_REPORTE 
  ,COD_FORMATO 
  ,FEC_DESDE 
  ,FEC_HASTA 
) VALUES (
   PV_NOM_REPORTE 
  ,PI_NOM_USUARIO 
  ,PV_DES_REPORTE 
  ,PI_COD_FORMATO
  ,PV_FEC_DESDE 
  ,PV_FEC_HASTA 
  );
   -- SELECCIONAR EL MAXIMO INSERTADO EN LA TABLA AGENDA 
SELECT @COD_REPORTE := MAX(COD_REPORTE) FROM RP_GENERALES;

IF EXISTS(SELECT * FROM RP_FORMATO WHERE COD_FORMATO = PI_COD_FORMATO)THEN
 BEGIN
 -- INSERTANDO EN LA TABLA REL REPORTE
INSERT INTO smartbanck.REL_REPORTES(
   COD_GENERALES 
  ,COD_FORMATOS 
  ,FEC_GENERADO
) VALUES (
   @COD_REPORTE
  ,PI_COD_FORMATO
  ,now() 
  );
  -- SELECCIONAR EL MAXIMO INSERTADO EN LA TABLA REL REPORTES 
SELECT @COD_REPORTES := MAX(COD_REPORTES) FROM REL_REPORTES;
 
 END; --  DEL BEGIN
 END IF;
 COMMIT;
END$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_GENERALES` (IN `PI_COD_REPORTE` BIGINT(20), IN `PV_NOM_REPORTE` VARCHAR(255), IN `PV_NOM_USUARIO` VARCHAR(255), IN `PV_DES_REPORTE` VARCHAR(255), IN `PI_COD_FORMATO` BIGINT(20), IN `PV_FEC_DESDE` DATETIME, IN `PV_FEC_HASTA` DATETIME)  BEGIN 
START TRANSACTION;

  UPDATE smartbanck.RP_GENERALES SET 
     
   NOM_REPORTE = PV_NOM_REPORTE   
  ,NOM_USUARIO = PV_NOM_USUARIO
  ,DES_REPORTE = PV_DES_REPORTE  
  ,COD_FORMATO = PI_COD_FORMATO   
  ,FEC_DESDE = PV_FEC_DESDE 
  ,FEC_HASTA = PV_FEC_HASTA 
  WHERE COD_REPORTE=PI_COD_REPORTE;
  select @COD_REPORTE := max(COD_REPORTE) FROM RP_GENERALES;
 
COMMIT;
END$$

